version: "3.7"

services:
  desktop:
    build:
      context: ./build
      args:
        USERID: ${USERID}
        GROUPID: ${GROUPID}
        USERLOGIN: ${USERLOGIN}
    volumes:
      - ${HOME}:/home/user/host
    ports:
      - "127.0.0.1:3389:3389/tcp"
