version: "3.7"

services:
  code.local:
    build:
      context: ./build
      args:
        USERID: ${USERID}
        GROUPID: ${GROUPID}
        USERLOGIN: ${USERLOGIN}
      target: code
    volumes:
      - ${HOME}:/home/${USERLOGIN}/host

  desktop:
    build:
      context: ./build
      args:
        USERID: ${USERID}
        GROUPID: ${GROUPID}
        AUDIOID: ${AUDIOID}
        VIDEOID: ${VIDEOID}
        DOCKERID: ${DOCKERID}
        USERLOGIN: ${USERLOGIN}
        PASSWORD: ${PASSWORD}
        TIMEZONE: ${TIMEZONE}
        I3THEME: ${I3THEME}
    privileged: true
    # https://stackoverflow.com/questions/56218242/headless-chromium-on-docker-fails
    shm_size: "2G"
    environment:
        TZ: ${TIMEZONE}
    volumes:
      - /var/run/acpid.socket:/var/run/acpid.socket
      - ${HOME}:/home/${USERLOGIN}/host
    ports:
      - "127.0.0.1:3389:3389/tcp"
